using System;
using System.Drawing;
using System.IO;
using System.Reflection;

using NPlot;

namespace Chartoscope.ChartAreas
{
	public class PlotSample
    {
            protected NPlot.PlotSurface2D plotSurface;
            protected string infoText = "";

            public PlotSample()
            {
                    plotSurface = new NPlot.PlotSurface2D ();

                    // Set defaults for the sample plotSurface
                    plotSurface.AutoScaleAutoGeneratedAxes = false;
                    plotSurface.AutoScaleTitle = false;
                    //plotSurface.Canvas.ModifyBg (StateType.Normal);
                    plotSurface.Legend = null;
                   // plotSurface.Canvas.Name = "plotSurface";
                    //plotSurface.ShowCoordinates = true;
                    plotSurface.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
                    plotSurface.Title = "";
                    plotSurface.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            }

            public string InfoText
            {
                    get { return infoText; }
            }

            public NPlot.PlotSurface2D PlotSurface
            {
                    get { return plotSurface; }
            }

    }
}

