
// This file has been generated by the GUI designer. Do not modify.
namespace Chartoscope.Widgets
{
	public partial class MultiChart
	{
		private global::Gtk.Table table1;
		private global::Gtk.DrawingArea priceActionDrawingArea;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Chartoscope.Widgets.MultiChart
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Chartoscope.Widgets.MultiChart";
			// Container child Chartoscope.Widgets.MultiChart.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.priceActionDrawingArea = new global::Gtk.DrawingArea ();
			this.priceActionDrawingArea.Name = "priceActionDrawingArea";
			this.table1.Add (this.priceActionDrawingArea);
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
