
// This file has been generated by the GUI designer. Do not modify.
namespace Chartoscope.Widgets
{
	public partial class PriceActionChart
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Chartoscope.Widgets.PriceActionChart
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Chartoscope.Widgets.PriceActionChart";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnExposeEvent);
		}
	}
}
